#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /home/ubuntu/error_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/root /var/www/html/a error_page 404 /error_404.html; location = /error_404.html {root /home/ubuntu/error_404.html; internal;}'
service nginx start
