#!/usr/bin/env bash
# Manages a process
file="manage_my_process"
tmp="/var/run/my_process.pid"
if [[ $1 == "start" ]]
then
    touch "$tmp"
    bash ./"$file" &
    echo "$!" > "$tmp"
    echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
    kill "$(cat "$tmp")"
    rm "$tmp"
    echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
    kill "$(cat "$tmp")"
    rm "$tmp"
    touch "$tmp"
    bash ./"$file" &
    echo "$!" > "$tmp"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
