#!/usr/bin/env bash
# Makes up a story from /etc/passwd file
file="/etc/passwd"
IFS=:
while read l
do
    arr=($l)
    echo "The user ${arr[0]} is part of the ${arr[3]} gang, lives in ${arr[5]} and rides ${arr[6]}. ${arr[0]}'s place is protected by the passcode ${arr[1]}, more info about the user here: ${arr[4]}"
done < "$file"
