#!/usr/bin/env bash
# Checks if file exists or not
hb="./holbertonschool"
if [ -e "$hb" ]; then
    echo "holbertonschool file exists"
    if [ -s "$hb" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi

    if [ -f "$hb" ]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
