#!/usr/bin/env bash
# user is a superuser that can do anything on a Unix machine
# echo "worker_processes 4;events { worker_connections 1024;}http {server {listen 8080;}}" > /tmp/conf
# pkill apache2
# sudo -u nginx bash -c "nginx -c /tmp/conf"
pkill apache2
chmod o+rw /etc/nginx/nginx.conf /etc/nginx/sites-available/default
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
