#!/usr/bin/env bash
# user is a superuser that can do anything on a Unix machine
printf "worker_processes 4\u003Bevents { worker_connections 1024\u003B}http {server {listen 8080\u003B}}\n" > /tmp/conf
pkill apache2
sudo -u nginx bash -c "nginx -c /tmp/conf"
